plugins { id 'com.android.application' }
android { namespace 'com.conectfacil'; compileSdk 34
 defaultConfig { applicationId 'com.conectfacil'; minSdk 29; targetSdk 34; versionCode 1; versionName '1.0' }
 buildFeatures { viewBinding true }
}
dependencies { implementation 'androidx.appcompat:appcompat:1.7.0' }
